on:
  workflow_dispatch:
    inputs:
      hello:
        description: "just testing"
        required: true
        type: string
name: Task
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo hello
          sleep 60
